---
title: "Group Assignment"
author: "Group 24"
format:
  html:
    embed-resources: true
editor: visual
---

# PCA tidyverse style

Load libraries

```{r setup, include=TRUE, message=FALSE, warning=FALSE}
# Load the libraries
library(tidyverse)
library(dplyr)
library(ggplot2)
library(broom)
library(ggrepel)
library(purrr)
```

Load data

```{r}
raw_dir <- "data/_raw/"
data_file <- "gravier.RData"
data_loc <- "https://github.com/ramhiser/datamicroarray/raw/master/data/"

if( !dir.exists(raw_dir) ){
  dir.create(path = raw_dir)
}
if( !file.exists(str_c(raw_dir, data_file)) ){
  download.file(
    url = str_c(data_loc, data_file),
    destfile = str_c(raw_dir, data_file))
}
load(file = str_c(raw_dir, data_file))
```

Data Wrangeling
```{r}
gravier <- gravier |>
  bind_cols() |>
  as_tibble() |> 
  mutate(y = case_when(y == "poor" ~ 1,
                       y == "good" ~ 0)) |> 
  relocate(early_metastasis = y)

```

Plot average expressions
```{r}
gravier |>
  select(-early_metastasis) |>
  summarise(across(everything(), mean, na.rm = TRUE)) |>
  pivot_longer(cols = everything(),
               names_to = "gene",
               values_to = "average_expression") |> 
  arrange(-average_expression) |>
  ggplot(aes(x = reorder(gene, average_expression), 
             y = average_expression)) + 
  geom_col() +
  labs(
    title = "Distribution of Average log2 Expression of Genes",
    x = "Genes",
    y = "Average log2 Expression"
  ) +
  theme_minimal()+
  theme(axis.text.x = element_blank())
```
